### ISSUE TITLE
Develop pattern for "unpacking" Attribute maps into actual CRD Fields

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#109]
The SNS API has a [`CreateTopic`](https://docs.aws.amazon.com/sns/latest/api/API_CreateTopic.html) API call.

The HTTP request seems simple. There's a `Name` query string parameter for the topic name and one of more "Attributes" query string parameter pairs. These attribute parameter pairs are a `map[string]*string` that ends up being added as a CRDField with the name `Attributes` in the `Topic` CRD's `TopicSpec` struct.

The problem is that this "Attributes" field isn't a free-form `map[string]string` like AWS Resource Tags. No, no. These are actually specific properties of the Topic. These properties can be set when creating a Topic:

* `DeliveryPolicy` – The policy that defines how Amazon SNS retries failed deliveries to HTTP/S endpoints.
* `DisplayName` – The display name to use for a topic with SMS subscriptions.
* `Policy` – The policy that defines who can access your topic. By default, only the topic owner can publish or subscribe to the topic.
* `KmsMasterKeyId` - The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK.

The DeliveryPology` and `Policy` attributes have other constraints on the values of the attribute; in other words, they are Enums.

Even more problematic is that there are a set of **Read Only** attributes that are returned from the `GetTopicAttributes` API call:

* `Owner` – The AWS account ID of the topic's owner.
* `SubscriptionsConfirmed` – The number of confirmed subscriptions for the topic.
* `SubscriptionsDeleted` – The number of deleted subscriptions for the topic.
* `SubscriptionsPending` – The number of subscriptions pending confirmation for the topic.
* `TopicArn` – The topic's ARN.
* `EffectiveDeliveryPolicy` – The JSON serialization of the effective delivery policy, taking system defaults into account.

The reason that these "Attributes" are problematic is that the Go type of the `aws-sdk-go` `CreateTopicInput.Attributes` is just a `map[string]*string` but the contents of this map is actually real, constrained schema properies, not just a free-form map of strings values.

For APIs like this that masquerade real, schema'd properties as a free-form `map[string]*string`, we should make the end-user experience for Kubernetes/ACK users better.

Instead of a `Topic` CR that looks like this:

```yaml
apiVersion: v1alpha1
kind: sns.services.k8s.aws
metadata:
  name: MyTopic
  namespace: my-app
spec:
  name: MyTopic
  attributes:
    DisplayName: MyDisplayTopic
    DeliveryPolicy: {"http":{"defaultHealthyRetryPolicy":{"numRetries":5}}}
```

I think a better user experience -- that doesn't require the user going and reading AWS documentation instead of just looking at the CRD's OpenAPI Schema validation -- would be a `Topic` CR that looks like this:

```yaml
apiVersion: v1alpha1
kind: sns.services.k8s.aws
metadata:
  name: MyTopic
  namespace: my-app
spec:
  name: MyTopic
  displayName: MyDisplayTopic
  deliveryPolicy:
    http:
      defaultHealthyRetryPolicy:
        numRetries:5
```

Of course, in order to get the above user experience, we're going to need a couple things:

1) Instructions to the code generator that the `Topic.Attributes` field should be ignored for the purposes of constructing the `TopicSpec` structure

2) That the `GetAttributes` SNS API call is used for retrieving actual schema'd properties and that those schema'd properties, returned in a raw `map[string]*string` should be treated as actual `TopicSpec` CRD fields.

3) The `CreateTopic` API call also only returns the TopicARN. If we want to grab the other Attributes (the ones that are Read Only), we need to do an additional call to `GetTopicAttributes` **after** getting a response from the `CreateTopic` call.
