### ISSUE TITLE
Generating CRDs leads to invalid CRD definitions

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#121]
If you run `./scripts/build-controller.sh apigatewayv2`, afterwards you will have a set of CRD manifests in `services/apigatewayv2/apis/v1alpha1/config/crd/`:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ ll services/apigatewayv2/apis/v1alpha1/config/crd/
total 120
drwxr-xr-x 2 jaypipes jaypipes  4096 Jul 31 13:40 ./
drwxr-xr-x 3 jaypipes jaypipes  4096 Jul 31 10:25 ../
-rw-r--r-- 1 jaypipes jaypipes  4892 Jul 31 13:32 apigatewayv2.services.k8s.aws_apimappings.yaml
-rw-r--r-- 1 jaypipes jaypipes  6307 Jul 31 13:40 apigatewayv2.services.k8s.aws_apis.yaml
-rw-r--r-- 1 jaypipes jaypipes  5483 Jul 31 13:32 apigatewayv2.services.k8s.aws_authorizers.yaml
-rw-r--r-- 1 jaypipes jaypipes  5102 Jul 31 13:32 apigatewayv2.services.k8s.aws_deployments.yaml
-rw-r--r-- 1 jaypipes jaypipes  5677 Jul 31 13:32 apigatewayv2.services.k8s.aws_domainnames.yaml
-rw-r--r-- 1 jaypipes jaypipes  5353 Jul 31 13:32 apigatewayv2.services.k8s.aws_integrationresponses.yaml
-rw-r--r-- 1 jaypipes jaypipes  6001 Jul 31 13:32 apigatewayv2.services.k8s.aws_integrations.yaml
-rw-r--r-- 1 jaypipes jaypipes  4877 Jul 31 13:32 apigatewayv2.services.k8s.aws_models.yaml
-rw-r--r-- 1 jaypipes jaypipes  5281 Jul 31 13:32 apigatewayv2.services.k8s.aws_routeresponses.yaml
-rw-r--r-- 1 jaypipes jaypipes  5636 Jul 31 13:32 apigatewayv2.services.k8s.aws_routes.yaml
-rw-r--r-- 1 jaypipes jaypipes  6625 Jul 31 13:32 apigatewayv2.services.k8s.aws_stages.yaml
-rw-r--r-- 1 jaypipes jaypipes  5273 Jul 31 13:32 apigatewayv2.services.k8s.aws_vpclinks.yaml
```

If you attempt to install any of the CRD manifests, however, you will run into the following error:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ ./build/tmp-34eceaac-apigwv2/kubectl apply -f services/apigatewayv2/apis/v1alpha1/config/crd/apigatewayv2.services.k8s.aws_apis.yaml 
error: error validating "services/apigatewayv2/apis/v1alpha1/config/crd/apigatewayv2.services.k8s.aws_apis.yaml": error validating data: ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus; if you choose to ignore these errors, turn validation off with --validate=false
```

The issue is that the generated CRD definition's `Status` field is misformed:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ tail -n6 services/apigatewayv2/apis/v1alpha1/config/crd/apigatewayv2.services.k8s.aws_apis.yaml 
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
```

You need to manually change the above `null`s to `[]`:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ tail -n6 services/apigatewayv2/apis/v1alpha1/config/crd/apigatewayv2.services.k8s.aws_apis.yaml 
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

and then you can install the CRD successfully:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ ./build/tmp-34eceaac-apigwv2/kubectl apply -f services/apigatewayv2/apis/v1alpha1/config/crd/apigatewayv2.services.k8s.aws_apis.yaml 
customresourcedefinition.apiextensions.k8s.io/apis.apigatewayv2.services.k8s.aws created
```

We need to investigate if this is a bug in `controller-gen` (I suspect it is) where `controller-gen crd:allowDangerousTypes=true paths=./...` invocation is producing invalid CRDs.
