### ISSUE TITLE
AWS Account information missing during reconciliation.

### ISSUE THREAD

**Issue by vijtrip2** [aws/aws-controllers-k8s#126]
**Describe the bug**
While running reconciler, the AWSAccountId is empty.

**Steps to reproduce**
Start the ack controller for APIGatewayV2 and ```kubectl create -f httpapisample.yaml```

*httpapisample.yaml*
```
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: httpapi-sample
spec:
  name: httpapi-sample
```

The code in reconciler.go for ```getOwnerAccountID()``` needs to return correct accountId.

**Expected outcome**
I am not sure if this issue will be resolved as part of https://github.com/aws/aws-controllers-k8s/issues/102, creating a separate. Please resolve this issue if it is duplicate of issue#102
