### ISSUE TITLE
Input YAML validation

### ISSUE THREAD

**Issue by nmvk** [aws/aws-controllers-k8s#162]
**Is your feature request related to a problem?**
I was able to create request with invalid YAML file (Though syntactically correct)

**Format of invalid YAML**
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: CacheParameterGroup
metadata:
  name: test-pg
spec:
  properties:
    cacheParameterGroupFamily: redis5.0 
    cacheParameterGroupName: test-pg
    description: test
```

**Format of correct YAML**
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: CacheParameterGroup
metadata:
  name: test-pg
spec:
    cacheParameterGroupFamily: redis5.0 
    cacheParameterGroupName: test-pg
    description: test
```

You can see that wrapping the `CreateCacheParameter` with `properties` ends up returning `nil` when generated code would call `r.ko.Spec.CacheParameterGroupName`.

**Describe the solution you'd like**
Throw user error, so they can fix the YAML file.

**Describe alternatives you've considered**
N/A
