### ISSUE TITLE
Create resource examples

### ISSUE THREAD

**Issue by rothgar** [aws/aws-controllers-k8s#171]
We should have an `/examples` repo with the different resources we have controllers for. This way if someone deploys a controller they can easily test creating one of the resources.

**Comment by rothgar** [comment]
Before I add anything, does this look like the correct syntax for tags and encryption config? I'm not 100% sure how the nested tag properties should be.

```
---
apiVersion: "ecr.services.k8s.aws/v1alpha1"
kind: Repository
metadata:
    name: "test-repository-from-ack"
spec:
    repositoryName: "test-repository-from-ack"
    encryptionConfiguration:
        encryptionType: AES256
    imageScanningConfiguration:
        scanOnPush: false
    tags:
    - tag1:
        key: "is-encrypted"
        value: "true"
    - tag2:
        key: "is-scanned"
        value: "false"
```
