### ISSUE TITLE
[Elasticache] ReplicationGroup endpoint not visible

### ISSUE THREAD

**Issue by nmvk** [aws/aws-controllers-k8s#230]
**Describe the bug**
After creating `ReplicationGroup` I was not able to see the `ConfigurationEndpoint` Address and port information.

```
kubectl describe replicationgroup/test-rg
Name:         test-rg
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"elasticache.services.k8s.aws/v1alpha1","kind":"ReplicationGroup","metadata":{"annotations":{},"name":"test-rg","namespace":...
API Version:  elasticache.services.k8s.aws/v1alpha1
Kind:         ReplicationGroup
Metadata:
  Creation Timestamp:  2020-08-20T23:37:25Z
  Finalizers:
    finalizers.elasticache.services.k8s.aws/ReplicationGroup
  Generation:        1
  Resource Version:  5263393
  Self Link:         /apis/elasticache.services.k8s.aws/v1alpha1/namespaces/default/replicationgroups/test-rg
  UID:               UUID
Spec:
  Automatic Failover:             true
  Cache Node Type:                cache.t3.medium
  Engine:                         redis
  Num Node Groups:                3
  Replicas Per Node Group:        2
  Replication Group Description:  test
  Replication Group ID:           test-rg
Events:                           <none>
```
**Steps to reproduce**
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: test-rg
spec:
    engine: redis 
    replicationGroupID: test-rg
    replicationGroupDescription: test
    automaticFailover: true
    cacheNodeType: cache.t3.medium
    numNodeGroups: 3
    replicasPerNodeGroup: 2
```
**Expected outcome**
Get Elasticache endpoint and port information

**Environment**

* Kubernetes version 1.17
* Using EKS (yes/no), if so version?  EKS 1.17
* AWS service targeted Elasticache
