### ISSUE TITLE
Enable support for ElastiCache ListAllowedNodeTypeModifications API

### ISSUE THREAD

**Issue by kumargauravsharma** [aws/aws-controllers-k8s#263]
**Is your feature request related to a problem?**
Enable support for ElastiCache ListAllowedNodeTypeModifications API
API reference: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/list-allowed-node-type-modifications.html

The response from this API helps in determining CacheNodeType input value for ModifyReplicationGroup API.

As the API takes ReplicationGroupId argument and provides the possible values for CacheNodeType, it is related to replication group custom resource.

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by kumargauravsharma** [comment]
Solution approach for review:

As the information provided by ListAllowedNodeTypeModifications API is related to ReplcationGroup custom resource; if generator config supports:
```
  ReplicationGroup:
    addon_annotations_operations:
      ListAllowedNodeTypeModifications:
        - CreateReplicationGroup
        - DescribeReplicationGroups
        - ModifyReplicationGroup
```
where it specifies that `ListAllowedNodeTypeModifications` is an addon operation to be invoked when Create/Modify/Describe ReplicationGroup operation is invoked, and save the result as annotation on target resource (ReplicationGroup).
