### ISSUE TITLE
Map computed properties from output shape to CRD's status

### ISSUE THREAD

**Issue by kumargauravsharma** [aws/aws-controllers-k8s#282]
**Is your feature request related to a problem?**
While populating CRD's status field for `ReplicationGroup` output shape, the properties like `ReplicasPerNodeGroup` are not populated/computed. It can be computed using `Status.NodeGroups` from output shape.

And as the `GoCodeSetOutput` logic copies the `r.ko` (desired state) into returned value `ko`
```
        // Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()
```
the reconciler fails to identify change in such properties when applied using `kubectl apply -f updated_resource.yaml`
and no update call is made.

**Describe the solution you'd like**
Enhance generator.yaml to specify the mapping of output shape properties to CRD's status properties or allowing custom code invocation during `GoCodeSetOutput` to help services implement the custom logic for such scenarios.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by kumargauravsharma** [comment]
Possible solution:
Enhance `generator.yaml` to specify custom code invocation during `GoCodeSetOutput `to help services implement the custom logic. This is generic solution which can be used for any service in ACK.

For ElastiCache ReplicationGroup, the updated `generator.yaml` will look like:
```
resources:
  ReplicationGroup:
    custom_set_output_operation:
      GoCodeCustomSetOutput
```
and an implementation for `GoCodeCustomSetOutput` operation will be provided inside `aws-controllers-k8s/services/elasticache/pkg/resource/replication_group/custom_set_output.go` file and it will be invoked from `crd.go::GoCodeSetOutput`.

Thus the fields that are part of resource spec (due to create API input but do not have direct mapping in describe API output) will be properly retrieved from response object and improve the reconciler update code flow to identify changes/diffs in `desired`, `latest` states.

**Comment by kumargauravsharma** [comment]
Considering that different operations (create, read, update) on a custom resource can have different output shapes, the custom set output needs to process output shape; thus updated generator.yaml would look like:
```
resources:
  ReplicationGroup:
    output_shapes:
      ReplicationGroup:
        custom_set_output_operation: CustomSetReplicationGroupOutput
```

This can be read as: For resource `ReplicationGroup` the output shape `ReplicationGroup` has custom set output operation `CustomSetReplicationGroupOutput`.

**Comment by kumargauravsharma** [comment]
Alternative generator.yaml
```
operations:
  DescribeReplicationGroups:
    custom_set_output_operation: CustomDescribeReplicationGroupsSetOutput
  CreateReplicationGroup:
    custom_set_output_operation: CustomCreateReplicationGroupSetOutput
  ModifyReplicationGroup:
    custom_set_output_operation: CustomModifyReplicationGroupSetOutput
```
This can be read as: For operation `CreateReplicationGroup` custom set output operation is `CustomCreateReplicationGroupSetOutput`
