### ISSUE TITLE
Replica count logic fix for Redis Cluster mode enabled

### ISSUE THREAD

**Issue by nmvk** [aws/aws-controllers-k8s#377]
**Describe the bug**
`NoOperationFault` while scaling up ReplicationGroup which is cluster mode enabled.

```
"controller": "replicationgroup", "request": "default/test", "error": "NoOperationFault: Requested new replica count already matches current number of replicas.\n\tstatus code: 400
```

Root cause seem to be related to utilizing role information in computation 

```
if latestShardMember.CurrentRole != nil && *latestShardMember.CurrentRole == "replica" {
    latestReplicaCount++
}
```
**Steps to reproduce**

```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: test
spec:
    engine: redis 
    replicationGroupID: test
    replicationGroupDescription: test
    automaticFailover: true
    cacheNodeType: cache.t3.micro
    numNodeGroups: 2
    replicasPerNodeGroup: 1
```

Change `cacheNodeType` to `cache.t3.small`

**Expected outcome**
Scale up modification

**Environment**

* Kubernetes version 1.17
* Using EKS (yes/no), if so version? Yes
* AWS service targeted (S3, RDS, etc.) Elasticache
