### ISSUE TITLE
Replication group create leads to invalid memory address or nil pointer dereference error

### ISSUE THREAD

**Issue by kumargauravsharma** [aws/aws-controllers-k8s#427]
**Describe the bug**

Replication group create leads to invalid memory address or nil pointer dereference error

**Steps to reproduce**

Create a replication group using sample yaml as:
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: test
spec:
    engine: redis 
    replicationGroupID: test
    replicationGroupDescription: test
    multiAZEnabled: false
    cacheNodeType: cache.t3.micro
    numNodeGroups: 3
    atRestEncryptionEnabled: true
    transitEncryptionEnabled: true
    cacheSubnetGroupName: default
    nodeGroupConfiguration:
      - 
        nodeGroupID: "0020"
        primaryAvailabilityZone: us-east-1a
        replicaAvailabilityZones:
          - us-east-1b
          - us-east-1c
        replicaCount: 2
      - 
        nodeGroupID: "0090"
        primaryAvailabilityZone: us-east-1b
        replicaAvailabilityZones:
          - us-east-1a
        replicaCount: 1
      - 
        nodeGroupID: "0290"
        primaryAvailabilityZone: us-east-1b
        replicaAvailabilityZones:
          - us-east-1a
          - us-east-1b
        replicaCount: 2
```

Observe logs with error:
```
runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 364 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic (http://k8s.io/apimachinery/pkg/util/runtime.logPanic)(0x223aee0, 0x2f91f60)
...
...
github.com/aws/aws-controllers-k8s/services/elasticache/pkg/resource/replication_group/resource.go:50 (http://github.com/aws/aws-controllers-k8s/services/elasticache/pkg/resource/replication_group/resource.go:50) +0x5
github.com/aws/aws-controllers-k8s/pkg/runtime.(reconciler).updateCRStatus(0xc0005f1290, 0x2643200, 0xc000042050, 0x264b660, 0xc0005a0128, 0x264b660, 0x0, 0xc000587410, 0x264b660)
```

**Expected outcome**
Create replication group to succeed with no nil pointer error.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? no
* AWS service targeted (S3, RDS, etc.): ElastiCache
