### ISSUE TITLE
Generate crds when running kustomize build services/${SERVICE}/config/default

### ISSUE THREAD

**Issue by ricardo-larosa** [aws/aws-controllers-k8s#468]
**Is your feature request related to a problem?**
Currently when you run `kustomize build services/${SERVICE}/config/default` it does not generate the crds.

**Describe the solution you'd like**
Run `kustomize build services/${SERVICE}/config/default` and crds are generated.

**Comment by jaypipes** [comment]
Hi @ricardo-larosa! We were manually installing the CRDs here:

https://github.com/aws/aws-controllers-k8s/blob/main/scripts/kind-build-test.sh#L166-L171

Because we kept running into validation failures due to using controller-gen <0.4.0. I think now that we have standardized on controller-gen@v0.4.0, we should be able to do what you're doing in #469...

**Comment by ricardo-larosa** [comment]
The main reason of request is not the ability of running of running `kustomize build .` in this repo. It is the ability of using a remote resource.

So I can do something like this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ack-s3-system

resources:
- git::git@github.com:aws/aws-controllers-k8s/services/s3/config/default

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: ack-s3-controller
  newName: my-registry/my-project/ack-s3-controller
  newTag: bcf0cdb
```
