### ISSUE TITLE
Generate printer columns for service controller CRDs

### ISSUE THREAD

**Issue by RedbackThomson** [aws/aws-controllers-k8s#561]
**Is your feature request related to a problem?**
The current printer column list contains only those defined by the defaults of K8s CRDs. It would be useful to define a set of custom printer columns, that would pull from spec or status, for any given resource. 

**Describe the solution you'd like**
An additional property in the `status_fields` that would enable/disable the addition of a printer column for the given status. However, this would allow only fields within the `status_fields` declaration to be a part of the printer columns, which would exclude the ability to add spec fields.

Example:
```yaml
resources:
  TrainingJob:
    status_fields:
    - operation_id: DescribeTrainingJob
      member_name: TrainingJobStatus
      printable_column: True
      ...
```

**Describe alternatives you've considered**
An addition to the service generator to support a list of printer columns, their types and their associated JSONPath within the resource.

This could be represented as such (using SageMaker training job as an example):
```yaml
resources:
  TrainingJob:
    status_fields:
    - operation_id: DescribeTrainingJob
      member_name: TrainingJobStatus
      ...
    printer_columns:
    - column_name: JobStatus
      type: String
      json_path: ".Status.TrainingJobStatus"
```
