### ISSUE TITLE
Custom properties targeting CRD fields in code generation config

### ISSUE THREAD

**Issue by muvaf** [aws/aws-controllers-k8s#585]
**Is your feature request related to a problem?**

I am trying to integrate referencers to Crossplane generation pipeline and that requires manually marking the fields that can be referenced. However, in `Config` object there is no easy way to target a field that can exist as top-level field (in `spec` directly) and a field that exists in sub-structs (the types in `types.go`). I have hit the same problem with [ignoring](https://github.com/aws/aws-controllers-k8s/pull/501) specific fields and workaround was to mark it on the SDK structs, i.e. `CreateApiInput.Name`. However, that only captures the top level fields and you have to list every call that has that field so that it doesn't appear in `Spec` at all.

Currently, the only way to provide customization to a field is through `resources[crdName].unpackAttributesMapConfig.fields[*]` but this applies only to attribute-style APIs.

**Describe the solution you'd like**
I would love it if we had a way to do the customizations targeting the field on the CRD, not SDK types. For example:
```yaml
resources:
  Table:
    customizations:
    - typeName: someSubstruct
      fieldName: ignoreMe
      properties:
      - type: Ignore
    - typeName: someSubstruct
      fieldName: fieldToBeReferenced
      properties:
      - type: Referencer
        referencedType: "ec2/v1alpha1/vpc"
    # for fields that exists in Spec
    - typeName: "."
      fieldName: topLevelField
      properties:
      - type: Referencer
        referencedType: "ec2/v1alpha1/securitygroup"
```

This way we can consolidate all customizations in one place with a nice DX. I believe this will come handy whenever ACK or Crossplane needs to have some custom logic for various reasons. We can add a new customization type and call it a day instead of expanding the `Config` struct for every case and from my experience working with AWS API, there are lots of customization points we'll need to do to provide a nice and usable UX for users.

**Describe alternatives you've considered**
An alternative could be to have different field for each customization type. For example:
```yaml
resources:
  Table:
    referenced_fields:
    - typeName: someSubstruct
      fieldName: fieldToBeReferenced
      referencedType: "ec2/v1alpha1/vpc"
    # for fields that exists in Spec
    - typeName: "."
      fieldName: topLevelField
      referencedType: "ec2/v1alpha1/securitygroup"
    ignored_fields:
    - typeName: someSubstruct
      fieldName: ignoreMe
```
