### ISSUE TITLE
Ability to customize properties of lower level fields in CRD spec

### ISSUE THREAD

**Issue by muvaf** [aws/aws-controllers-k8s#655]
**Is your feature request related to a problem?**

We are able to customize field properties in [`Config` object](https://github.com/aws/aws-controllers-k8s/blob/a50dfbb/pkg/generate/config/resource.go#L63) but that covers only the top-level fields. We are not able to give custom properties for the fields of the structs defined in `types.go`.

**Describe the solution you'd like**

I would like to be able to do this in a way similar to the existing mechanism. But it's a bit complicated because multiple CRDs might be using the same struct but current field customization API works on CRD-level. However, this may not be as important since most of the time if two CRDs are using the same struct, the customization would work in favor of both of them. Something similar to the following could be a solution:
```yaml
resources:
  Backup:
    fields:
      ".TableName":
        is_required: true
      "AttributeDefinition.AttributeType":
        is_required: true
```
or

```yaml
# a top-level struct in Config
fields:
  "AttributeDefinition.AttributeType":
    is_required: true
  "Table.TableName":
    is_required: true
```

**Describe alternatives you've considered**

Additionally, in the code, we can inline the top level struct in `TableSpec` instead of listing all of the top fields there so that every struct we are concerned would be located in `types.go`, hence a single point to do all of these operations with a single API.
