### ISSUE TITLE
Create IAM role for a pod and associating it with the pod service account via IAM OIDC 

### ISSUE THREAD

**Issue by cpaika** [aws/aws-controllers-k8s#7]
**Is your feature request related to a problem?**
I have a pipeline that deploys a Kubernetes pod to a cluster.  I want that pod to have an IAM role, to interact with AWS resources.  Currently theres no way (that I know of, I'd love to be wrong) to both create an IAM role and associate with the pod in the same deployment manifest file

**Describe the solution you'd like**
An IAM operator that exports the IAM role, to be used in the other part of the manifest for associating with the pod

If anyone can think of another way to achieve this, please let me know

**Comment by mhausenblas** [comment]
Thanks for raising this issue @cpaika. 

> I want that pod to have an IAM role, to interact with AWS resources. Currently theres no way (that I know of, I'd love to be wrong) to both create an IAM role and associate with the pod in the same deployment manifest file.

What beyond [IAM roles for service accounts](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) (IRSA) is necessary? IRSA allows you to grant permissions on the pod level.

**Comment by dcherman** [comment]
@mhausenblas If I'm understanding it correctly, it's essentially a request for the `IAMRole` part of the operator so that you can declaratively create an `IAMRole` along with associated policies.  One of the outputs of that might be a `ServiceAccount` that is pre-configured to use IRSA like you mentioned, then you can just use `serviceAccountName` to use the generated role in you rpod.  Least that's what I'd want :)

**Comment by dylanenabled** [comment]
It'd be nice to be able to define an IAM policy via a k8s manifest, then using something like the k8s RBAC `RoleBinding` resource to bind that policy to a `serviceaccount` and have the operator create the policy, and role, then attach it to the serviceaccount automatically.

E.G (Something like this, based on the k8s RBAC example)
```
apiVersion: aws.serviceoperator/v1
kind: IAMRole
metadata:
  namespace: default
  name: s3-access
policies:
- inline:
    {
       # Policy document JSON/YAML inline allowing S3 access
    } 
- attached:
    arn: some:policy:arn
---
apiVersion: aws.serviceoperator/v1
kind: IAMRoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: s3-writer-service
  namespace: default
roleRef:
  kind: IAMRole
  name: s3-access 
```

Then the operator could see the `IAMRole` resource, create a cloudformation stack to make the IAM Role and attach the policies, then add the `eks.amazonaws.com/role-arn` role ARN annotation to the `s3-writer-service` Serviceaccount once the role is created.

**Comment by dylanenabled** [comment]
Actually now that I think about it you can only have one role per `ServiceAccount`, so it probably doesn't make sense to be able to attach multiple `IAMRoles` to a `ServiceAccount` - instead the operator should create a single IAM `Role` per `ServiceAccount` and attach the policies to it.

**Comment by dcherman** [comment]
@dylanenabled So without having thought extensively about this, one idea is that the creation of an `IAMRole` would also result in the creation of a `ServiceAccount` with the IAM role bound to it.  As part of that IAM role, you could define any inline policies that you wanted at creation time.

```yaml
apiVersion: aws.amazon.com/v1alpha1
kind: IAMRole
metadata:
  name: my-role
spec:
  policies: ...
```

Other resources like say an `S3Bucket` could have something like this:

```yaml
apiVersion: aws.amazon.com/v1alpha1
kind: S3Bucket
metadata:
  name: foo
spec:
  roles:
  - iamRoleRef:
       name: my-role
         policies:
           GetObject: *
  - iamRoleRef:
       name: another-created-role
         policies:
           PutObject: *      
```
